# Generated by Django 3.2.21 on 2023-09-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='wallet',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
