# Generated by Django 3.2.21 on 2023-09-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_deposit_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[['SUCCESSFUL', 'SUCCESSFUL'], ['PENDING', 'PENDING'], ['FAILED', 'FAILED'], ['CANCELED', 'CANCELED'], ['HOLD', 'HOLD']], default='PENDING', max_length=50),
        ),
    ]
