# Generated by Django 3.2.21 on 2023-09-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0004_auto_20230930_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
