# Generated by Django 4.2.5 on 2023-09-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
