# Generated by Django 4.2.5 on 2023-09-26 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifieds', '0002_alter_classified_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='owner',
            field=models.ForeignKey(default='c006fbb7-66d1-43ed-8308-05ac64e1715a', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
