# Generated by Django 3.2.21 on 2023-10-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_alter_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
